### ISSUE TITLE
Add "RINEX2" and "RINEX3" to the "Format"enumeration

### ISSUE THREAD

**Issue by toddking** [spase-group/spase-base-model#15]
Add Receiver INdependent EXchange (RINEX) version 2 and 3 "RINEX2" and "RINEX3" to the "Format" enumeration.

Specifcation:
RINEX2: https://kb.igs.org/hc/en-us/articles/115003980188-RINEX-2-11
RINEX3: https://files.igs.org/pub/data/format/rinex305.pdf

**Comment by tressahelvey** [comment]
Fixed in SPASE version 2.4.1
