### ISSUE TITLE
Add "TAP" ("EPN_TAP") to "Style" enumeration.

### ISSUE THREAD

**Issue by toddking** [spase-group/spase-base-model#17]
The TAP and EPN-TAP protocol for accessing data should be added to the "Style" enumeration.

Specification:
TAP: https://www.ivoa.net/documents/TAP/20190927/REC-TAP-1.1.html
        https://www.ivoa.net/documents/TAP/20190927/REC-TAP-1.1.pdf
EPN-TAP: https://www.ivoa.net/documents/EPNTAP/20210721/PR-EPNTAP-v2.0-20210721.pdf

**Comment by tressahelvey** [comment]
Issue resolved. Closing ticket.
