### ISSUE TITLE
Add fields in Access for filenaming and directory templates

### ISSUE THREAD

**Issue by candeynasa** [spase-group/spase-base-model#25]
Add fields in Access for filenaming and directory templates to store the patterns for the data filenames and directory structure, using the URI template specification [https://github.com/hapi-server/uri-templates/wiki/Specification](https://github.com/hapi-server/uri-templates/wiki/Specification). This will enable automated search of files matching a time range.  SPDF has its datasets described in [all.xml](https://spdf.gsfc.nasa.gov/pub/catalogs/all.xml) using the "%" specification of strptime, which can migrated to the "$" specification.

For instance, all.xml has:
```
<access filenaming="ac_or_def_%Y%m%d_%Q.cdf" protocol="https" subdividedby="%Y" timerange_start="1997-08-26 00:00:00" timerange_stop="2023-05-31 00:00:00">
<URL>https://cdaweb.gsfc.nasa.gov/pub/data/ace/orbit/level_2_cdaweb/def_or</URL>
```
and would use SPASE fields:
access_filenaming_template: "ac_or_def_$Y$m$d_v$v.cdf"
access_directory_template: "$Y"
URL: "https://spdf.gsfc.nasa.gov/pub/data/ace/orbit/level_2_cdaweb/def_or/"

Definition:
access_filenaming_template: Filenaming templates to store the patterns for the data filenames structure, using the URI template specification [https://github.com/hapi-server/uri-templates/wiki/Specification](https://github.com/hapi-server/uri-templates/wiki/Specification). This will enable automated search of files matching a time range.  For example, the ACE definitive orbit dataset at NASA SPDF has files following the naming pattern "ac_or_def_$Y$m$d_v$v.cdf", where $Y is the year, $m is the month, $d is the day, and $v is the version number.

access_directory_template: Directory hierarchy templates to store the patterns for the data directory structure, using the URI template specification [https://github.com/hapi-server/uri-templates/wiki/Specification](https://github.com/hapi-server/uri-templates/wiki/Specification). This will enable automated search of files matching a time range.  For example, the ACE definitive orbit dataset at NASA SPDF has yearly subdirectories for the data files following the naming pattern $Y.

Both are optional and go in the Access information sections, since they are specific to repositories.

**Comment by candeynasa** [comment]
Original [FTP finder Python code](https://spdf.gsfc.nasa.gov/pub/software/old/ftpfinder/)

**Comment by jbfaden** [comment]
I have Java, Python, and JavaScript codes which support these templates: https://github.com/hapi-server/uri-templates

**Comment by lfb12345** [comment]
In the example:

"ac_or_def_$Y$m$d_v$v.cdf", where $Y is the year, $m is the month, $d is the day, and $v is the version number.

wouldn't $d not be resolved due to fact that '_v' is appended yielding $d_v?

**Comment by jbfaden** [comment]
The syntax is either $L where L is a single letter, or $(LETTERS) where LETTERS can be a multi-letters word.  So if there are no parenthesis, then "d" identifies the field and everything up to the next $ (in $v) is the separator (_v in $d_v$v).  Note the $(LETTERS) form must be used when qualifiers are used with a field, so for example you might use $(d;pad=none).

**Comment by lfb12345** [comment]
I will be adding these tomorrow.

**Comment by jbfaden** [comment]
This still needs to be done.  During the SPASE meeting we looked on the website for the change and didn't see it.  AccessDirectoryTemplate does appear in the draft which Lee sent out on 
2023/07/19 18:45 UT email.

**Comment by tressahelvey** [comment]
@lfb12345 @jbfaden   Please confirm if this task is complete. Thank you. Tressa

**Comment by jbfaden** [comment]
I can confirm this is complete.
