### ISSUE TITLE
Changes to "History" section PDF

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/spase-base-model#28]
In History section: 
--fix misspellings; 
--4th history element should include a description of all the simulations that have been folded in (description of what those changes are)

**Comment by lfb12345** [comment]
I am not sure about the "4th history element". Misspellings fixed.

**Comment by tressahelvey** [comment]
Hello Lee,
I believe it was for the 2.6.1 history section.

If you look at 2.5.0, page 4 of PDF, this section:

4. The data environment is continuously evolving. New resources are actively generated either as part of an on‑going experiment or as a result of analysis and assessment. These new resources may be directly related to other resources. As new resources are generated or new associations defined the network or collections formed will expand over time.

It was suggested that we add something to explain that the simulations have been folded into the new 2.6.0 version.

Tressa



______________________________
Regards,
Tressa Helvey-Kasulke
NASA/Goddard Space Flight Center
Project Manager, HDRL
Cell: 202-870-4363

From: lfb12345 ***@***.***>
Sent: Sunday, July 9, 2023 8:48 AM
To: spase-group/spase-base-model ***@***.***>
Cc: Helvey-Kasulke, Tressa L. (GSFC-672.0)[ASRC FEDERAL SYSTEM SOLUTIONS] ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [spase-group/spase-base-model] Changes to "History" section PDF (Issue #28)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



I am not sure about the "4th history element". Misspellings fixed.

**Comment by tressahelvey** [comment]
Complete
