### ISSUE TITLE
Changes to Draft 2.6.0 Documents

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/spase-base-model#29]
1. Add a sentence in "DurationDescription" to add the word “cadence”. (page 14) 
Concept of cadence needs to be introduced under duration description in pdf version of SPASE model.

2. Also in this section, rewrite to remove “midnight” as time 

3. Make ISO 8601 a live link

**Comment by lfb12345** [comment]
These issues have been addressed and will be closed after discussion.

**Comment by tressahelvey** [comment]
Assigning to Shing to validate changes.

**Comment by tressahelvey** [comment]
closed
