### ISSUE TITLE
Provider Processing Level details

### ISSUE THREAD

**Issue by toddking** [spase-group/spase-base-model#9]
External documentation to explain the processing levels should be referenced by a URL that is part of the "ProviderProcessingLevel" section. In 2.4.0, an InformationURL is not tightly coupled to a particular which makes the associations vague.

**Comment by tressahelvey** [comment]
Per Shing: We should be referring back to the provider processing level documentation, example: CMAD

**Comment by tressahelvey** [comment]
After discussion, data providers need to self regulate their text fields and be consistent as a best practices. Closing ticket.
